objects/Apex_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Record_URL__c</fullName>
        <label>Record URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <label>User Email</label>
        <type>Email</type>
    </fields>
    <label>Apex Error Log</label>
    <nameField>
        <displayFormat>AEL-{00}</displayFormat>
        <label>Apex Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Platform_Log_Event__e.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_URL__c</fullName>
        <label>Record URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Email__c</fullName>
        <label>User Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Platform Log Event</label>
    <pluralLabel>Platform Log Events</pluralLabel>
</CustomObject>

classes/PlatformEventLogService.cls
/**
* @group Error Logging
* @description Service class for Platform Event Log Platform Event object
* @author Vamsi Velampati (vvelampati@deloitte.com)
* @date 05/25/2020
* @version 1.0
*/
public class PlatformEventLogService {
  
    private static PlatformEventLogService instance = null;
    
    public static PlatformEventLogService getInstance(){
        if(instance == null){
            instance = new PlatformEventLogService();
        }
        
        return instance;
    }
    
    public void logEventsFromList(List<Platform_Log_Event__e> logEventsList){
        List<Apex_Error_Log__c> errorLogs = new List<Apex_Error_Log__c>();
        
        for(Platform_Log_Event__e logEvent : logEventsList){
            Apex_Error_Log__c logLineItem = new Apex_Error_Log__c();
          
            logLineItem.Class_Name__c = logEvent.Class_Name__c;
            logLineItem.Exception_Type__c = logEvent.Exception_Type__c;
            logLineItem.Level__c = logEvent.Level__c;
            logLineItem.Line_Number__c = logEvent.Line_Number__c;
            logLineItem.Message__c = logEvent.Message__c;
            logLineItem.Method__c = logEvent.Method__c;
            logLineItem.Record_URL__c = logEvent.Record_URL__c;
            logLineItem.Stack_Trace__c = logEvent.Stack_Trace__c;
            logLineItem.User_Email__c = logEvent.User_Email__c;
            
            errorLogs.add(logLineItem);
        }
        
        insert errorLogs;
    }
   	
    public void logEventsFromMap(Map<Id,Platform_Log_Event__e> platformEventsMap){
        
    }
    
    public void logEvents(List<Platform_Log_Event__e> platformEventsList, Map<Id, Platform_Log_Event__e> platformEventsMap){
        
    }
}